namespace GrafcetStudioAIMockService {
  export type MockErrorFixtureName = 'malformed-json' | 'wrong-proposal-shape';
  export type MockFixtureName = GrafcetStudioAIContracts.AiIntent | MockErrorFixtureName;

  export interface MockAiResponse {
    ok: boolean;
    rawText: string;
    proposal?: GrafcetStudioAIContracts.AiProposal;
    fixtureName: MockFixtureName;
    errors: string[];
  }

  export interface GenerateMockResponseOptions {
    fixtureName?: MockFixtureName;
    proposalId?: string;
  }

  export interface MockServiceApi {
    readonly fixtures: readonly MockFixtureName[];
    getFixtureRawText(name: MockFixtureName): string;
    getFixtureProposal(intent: GrafcetStudioAIContracts.AiIntent, requestId?: string, proposalId?: string): GrafcetStudioAIContracts.AiProposal;
    generateMockResponse(request: GrafcetStudioAIContracts.AiRequest, options?: GenerateMockResponseOptions): MockAiResponse;
    receiveHostResponse(rawText: string): MockAiResponse;
    validateMockFixtures(): MockFixtureValidationResult;
  }

  export interface MockFixtureValidationResult {
    ok: boolean;
    validFixtures: GrafcetStudioAIContracts.AiIntent[];
    invalidFixtures: MockErrorFixtureName[];
    errors: string[];
  }

  const validFixtureNames: readonly GrafcetStudioAIContracts.AiIntent[] = ['create-variable', 'clone-variable', 'map-io', 'create-flow', 'create-structure'];
  const errorFixtureNames: readonly MockErrorFixtureName[] = ['malformed-json', 'wrong-proposal-shape'];
  const allFixtureNames: readonly MockFixtureName[] = ['create-variable', 'clone-variable', 'map-io', 'create-flow', 'create-structure', 'malformed-json', 'wrong-proposal-shape'];

  function clone<T>(value: T): T {
    return JSON.parse(JSON.stringify(value)) as T;
  }

  function makeProposalId(intent: GrafcetStudioAIContracts.AiIntent): string {
    return 'ai-prop-mock-' + intent.replace(/[^a-z0-9]+/g, '-') + '-' + Date.now().toString(36);
  }

  const validFixtures: Record<GrafcetStudioAIContracts.AiIntent, GrafcetStudioAIContracts.AiProposal> = {
    'create-variable': {
      schemaVersion: GrafcetStudioAIContracts.schemaVersion,
      id: 'ai-prop-mock-create-variable',
      intent: 'create-variable',
      status: 'draft',
      summary: 'Mock proposal creates one manual boolean variable for parser, preview, and apply tests.',
      warnings: ['Mock fixture only; no project mutation has been performed.'],
      data: {
        bucket: 'user',
        variable: {
          label: 'Mock_StartCommand',
          format: 'BOOL',
          address: 'MR100',
          kind: 'primitive',
          dataType: 'BOOL',
          comment: 'Generated by mock AI fixture for create-variable.',
          source: 'manual'
        }
      }
    },
    'clone-variable': {
      schemaVersion: GrafcetStudioAIContracts.schemaVersion,
      id: 'ai-prop-mock-clone-variable',
      intent: 'clone-variable',
      status: 'draft',
      summary: 'Mock proposal clones Cylinder struct into 3 instances.',
      warnings: ['Mock fixture only.'],
      data: {
        source: { label: 'Cylinder' },
        variables: [
          { label: 'Cyl_A', format: 'Cylinder', kind: 'struct', comment: 'Clone A', source: 'manual' },
          { label: 'Cyl_B', format: 'Cylinder', kind: 'struct', comment: 'Clone B', source: 'manual' },
          { label: 'Cyl_C', format: 'Cylinder', kind: 'struct', comment: 'Clone C', source: 'manual' }
        ]
      }
    },
    'map-io': {
      schemaVersion: GrafcetStudioAIContracts.schemaVersion,
      id: 'ai-prop-mock-map-io',
      intent: 'map-io',
      status: 'draft',
      summary: 'Mock proposal maps one physical IO point to an application variable.',
      warnings: ['Mock fixture only; physical IO existence is checked later.'],
      data: {
        entries: [
          {
            physicalIOId: 'mock-io-start-button',
            appVariable: 'Mock_StartCommand',
            status: 'mapped',
            matchScore: 0.95
          }
        ]
      }
    },
    'create-flow': {
      schemaVersion: GrafcetStudioAIContracts.schemaVersion,
      id: 'ai-prop-mock-create-flow',
      intent: 'create-flow',
      status: 'draft',
      summary: 'Mock proposal creates a minimal two-step flow skeleton.',
      warnings: ['Mock fixture only; diagram graph insertion is handled by the apply layer.'],
      data: {
        flow: {
          id: 'mock-flow-basic-cycle',
          name: 'Mock Basic Cycle',
          type: 'Grafcet',
          mode: 'Auto',
          steps: [
            { id: 'mock-step-idle', number: 1, label: 'Idle', initial: true, actions: [] },
            { id: 'mock-step-run', number: 2, label: 'Run', initial: false, actions: [{ variable: 'Mock_StartCommand', qualifier: 'N', address: 'MR100' }] }
          ],
          transitions: [
            { id: 'mock-trans-start', label: 'Start', condition: 'Mock_StartCommand', fromStepIds: ['mock-step-idle'], toStepIds: ['mock-step-run'] }
          ],
          connections: [
            { from: 'mock-step-idle', to: 'mock-trans-start' },
            { from: 'mock-trans-start', to: 'mock-step-run' }
          ]
        }
      }
    },
    'create-structure': {
      schemaVersion: GrafcetStudioAIContracts.schemaVersion,
      id: 'ai-prop-mock-create-structure',
      intent: 'create-structure',
      status: 'draft',
      summary: 'Mock proposal creates a ServoAxis struct with Enable and Ready signals.',
      warnings: ['Mock fixture only; no project mutation has been performed.'],
      data: {
        name: 'ServoAxis',
        signals: [
          { name: 'Enable', dataType: 'Bool', varType: 'Output', comment: 'Enable servo axis' },
          { name: 'Ready', dataType: 'Bool', varType: 'Input', comment: 'Servo ready signal' },
          { name: 'Fault', dataType: 'Bool', varType: 'Input', comment: 'Servo fault signal' }
        ]
      }
    }
  };

  const malformedJsonFixture = '{ "schemaVersion": "' + GrafcetStudioAIContracts.schemaVersion + '", "intent": "create-variable", "data": { ';

  const wrongProposalShapeFixture = {
    schemaVersion: GrafcetStudioAIContracts.schemaVersion,
    id: 'ai-prop-mock-wrong-shape',
    intent: 'create-variable',
    status: 'draft',
    summary: 'This fixture intentionally fails AiProposal validation because data.variable is missing required fields.',
    data: {
      variable: {
        label: '',
        address: 123
      }
    }
  };

  function withRequest(value: GrafcetStudioAIContracts.AiProposal, requestId?: string, proposalId?: string): GrafcetStudioAIContracts.AiProposal {
    const proposal = clone(value);
    proposal.id = proposalId || makeProposalId(proposal.intent);
    if (requestId) proposal.requestId = requestId;
    return proposal;
  }

  export function getFixtureProposal(intent: GrafcetStudioAIContracts.AiIntent, requestId?: string, proposalId?: string): GrafcetStudioAIContracts.AiProposal {
    return withRequest(validFixtures[intent], requestId, proposalId);
  }

  export function getFixtureRawText(name: MockFixtureName): string {
    if (name === 'malformed-json') return malformedJsonFixture;
    if (name === 'wrong-proposal-shape') return JSON.stringify(wrongProposalShapeFixture, null, 2);
    return JSON.stringify(getFixtureProposal(name), null, 2);
  }

  export function generateMockResponse(request: GrafcetStudioAIContracts.AiRequest, options?: GenerateMockResponseOptions): MockAiResponse {
    const requestValidation = GrafcetStudioAIContracts.validateAiRequest(request);
    if (!requestValidation.ok) {
      return {
        ok: false,
        rawText: '',
        fixtureName: options && options.fixtureName ? options.fixtureName : 'wrong-proposal-shape',
        errors: requestValidation.errors
      };
    }

    const fixtureName = options && options.fixtureName ? options.fixtureName : request.intent;
    const rawText = fixtureName === 'malformed-json'
      ? malformedJsonFixture
      : fixtureName === 'wrong-proposal-shape'
        ? JSON.stringify(wrongProposalShapeFixture, null, 2)
        : JSON.stringify(getFixtureProposal(fixtureName, request.id, options ? options.proposalId : undefined), null, 2);

    const parsed = GrafcetStudioAIProposalParser.parseAiProposalResponse(rawText);
    return parsed.ok
      ? { ok: true, rawText, proposal: parsed.value, fixtureName, errors: [] }
      : { ok: false, rawText, fixtureName, errors: parsed.errors };
  }

  export function receiveHostResponse(rawText: string): MockAiResponse {
    if (typeof rawText !== 'string' || !rawText.trim()) {
      return { ok: false, rawText: rawText || '', fixtureName: 'wrong-proposal-shape', errors: ['Host AI response must be a non-empty JSON string.'] };
    }

    const parsed = GrafcetStudioAIProposalParser.parseAiProposalResponse(rawText);
    if (!parsed.ok || !parsed.value) {
      const fixtureName: MockErrorFixtureName = parsed.jsonText ? 'wrong-proposal-shape' : 'malformed-json';
      return { ok: false, rawText, fixtureName, errors: parsed.errors };
    }

    return { ok: true, rawText, proposal: parsed.value, fixtureName: parsed.value.intent, errors: [] };
  }

  export function validateMockFixtures(): MockFixtureValidationResult {
    const errors: string[] = [];
    const validFixturesThatPassed: GrafcetStudioAIContracts.AiIntent[] = [];
    const invalidFixturesThatFailed: MockErrorFixtureName[] = [];

    validFixtureNames.forEach(function(intent) {
      const validation = GrafcetStudioAIContracts.validateAiProposal(validFixtures[intent]);
      if (validation.ok) validFixturesThatPassed.push(intent);
      else errors.push(intent + ' fixture should pass validation: ' + validation.errors.join('; '));
    });

    try {
      JSON.parse(malformedJsonFixture);
      errors.push('malformed-json fixture should fail JSON.parse.');
    } catch (_error) {
      invalidFixturesThatFailed.push('malformed-json');
    }

    const wrongShapeValidation = GrafcetStudioAIContracts.validateAiProposal(wrongProposalShapeFixture);
    if (!wrongShapeValidation.ok) invalidFixturesThatFailed.push('wrong-proposal-shape');
    else errors.push('wrong-proposal-shape fixture should fail AiProposal validation.');

    return {
      ok: errors.length === 0,
      validFixtures: validFixturesThatPassed,
      invalidFixtures: invalidFixturesThatFailed,
      errors
    };
  }

  export const api: MockServiceApi = {
    fixtures: allFixtureNames,
    getFixtureRawText,
    getFixtureProposal,
    generateMockResponse,
    receiveHostResponse,
    validateMockFixtures
  };
}
