"use strict";
var GrafcetStudioAIMockService;
(function (GrafcetStudioAIMockService) {
    const validFixtureNames = ['create-variable', 'clone-variable', 'map-io', 'create-flow'];
    const errorFixtureNames = ['malformed-json', 'wrong-proposal-shape'];
    const allFixtureNames = ['create-variable', 'clone-variable', 'map-io', 'create-flow', 'malformed-json', 'wrong-proposal-shape'];
    function clone(value) {
        return JSON.parse(JSON.stringify(value));
    }
    function makeProposalId(intent) {
        return 'ai-prop-mock-' + intent.replace(/[^a-z0-9]+/g, '-') + '-' + Date.now().toString(36);
    }
    const validFixtures = {
        'create-variable': {
            schemaVersion: GrafcetStudioAIContracts.schemaVersion,
            id: 'ai-prop-mock-create-variable',
            intent: 'create-variable',
            status: 'draft',
            summary: 'Mock proposal creates one manual boolean variable for parser, preview, and apply tests.',
            warnings: ['Mock fixture only; no project mutation has been performed.'],
            data: {
                bucket: 'user',
                variable: {
                    label: 'Mock_StartCommand',
                    format: 'BOOL',
                    address: 'MR100',
                    kind: 'primitive',
                    dataType: 'BOOL',
                    comment: 'Generated by mock AI fixture for create-variable.',
                    source: 'manual'
                }
            }
        },
        'clone-variable': {
            schemaVersion: GrafcetStudioAIContracts.schemaVersion,
            id: 'ai-prop-mock-clone-variable',
            intent: 'clone-variable',
            status: 'draft',
            summary: 'Mock proposal clones a selected variable with a new label and address.',
            warnings: ['Mock fixture only; source validation belongs to the apply layer.'],
            data: {
                source: { label: 'Existing_StartCommand' },
                variable: {
                    label: 'Mock_StartCommand_Clone',
                    format: 'BOOL',
                    address: 'MR101',
                    kind: 'primitive',
                    dataType: 'BOOL',
                    comment: 'Generated by mock AI fixture for clone-variable.',
                    source: 'manual'
                }
            }
        },
        'map-io': {
            schemaVersion: GrafcetStudioAIContracts.schemaVersion,
            id: 'ai-prop-mock-map-io',
            intent: 'map-io',
            status: 'draft',
            summary: 'Mock proposal maps one physical IO point to an application variable.',
            warnings: ['Mock fixture only; physical IO existence is checked later.'],
            data: {
                entries: [
                    {
                        physicalIOId: 'mock-io-start-button',
                        appVariable: 'Mock_StartCommand',
                        status: 'mapped',
                        matchScore: 0.95
                    }
                ]
            }
        },
        'create-flow': {
            schemaVersion: GrafcetStudioAIContracts.schemaVersion,
            id: 'ai-prop-mock-create-flow',
            intent: 'create-flow',
            status: 'draft',
            summary: 'Mock proposal creates a minimal two-step flow skeleton.',
            warnings: ['Mock fixture only; diagram graph insertion is deferred to the apply layer.'],
            data: {
                flow: {
                    id: 'mock-flow-basic-cycle',
                    name: 'Mock Basic Cycle',
                    type: 'Grafcet',
                    mode: 'Auto',
                    steps: [
                        { id: 'mock-step-idle', number: 1, label: 'Idle', initial: true, actions: [] },
                        { id: 'mock-step-run', number: 2, label: 'Run', initial: false, actions: [{ variable: 'Mock_StartCommand', qualifier: 'N', address: 'MR100' }] }
                    ],
                    transitions: [
                        { id: 'mock-trans-start', label: 'Start', condition: 'Mock_StartCommand', fromStepIds: ['mock-step-idle'], toStepIds: ['mock-step-run'] }
                    ],
                    connections: [
                        { from: 'mock-step-idle', to: 'mock-trans-start' },
                        { from: 'mock-trans-start', to: 'mock-step-run' }
                    ]
                }
            }
        }
    };
    const malformedJsonFixture = '{ "schemaVersion": "' + GrafcetStudioAIContracts.schemaVersion + '", "intent": "create-variable", "data": { ';
    const wrongProposalShapeFixture = {
        schemaVersion: GrafcetStudioAIContracts.schemaVersion,
        id: 'ai-prop-mock-wrong-shape',
        intent: 'create-variable',
        status: 'draft',
        summary: 'This fixture intentionally fails AiProposal validation because data.variable is missing required fields.',
        data: {
            variable: {
                label: '',
                address: 123
            }
        }
    };
    function withRequest(value, requestId, proposalId) {
        const proposal = clone(value);
        proposal.id = proposalId || makeProposalId(proposal.intent);
        if (requestId)
            proposal.requestId = requestId;
        return proposal;
    }
    function getFixtureProposal(intent, requestId, proposalId) {
        return withRequest(validFixtures[intent], requestId, proposalId);
    }
    GrafcetStudioAIMockService.getFixtureProposal = getFixtureProposal;
    function getFixtureRawText(name) {
        if (name === 'malformed-json')
            return malformedJsonFixture;
        if (name === 'wrong-proposal-shape')
            return JSON.stringify(wrongProposalShapeFixture, null, 2);
        return JSON.stringify(getFixtureProposal(name), null, 2);
    }
    GrafcetStudioAIMockService.getFixtureRawText = getFixtureRawText;
    function generateMockResponse(request, options) {
        const requestValidation = GrafcetStudioAIContracts.validateAiRequest(request);
        if (!requestValidation.ok) {
            return {
                ok: false,
                rawText: '',
                fixtureName: options && options.fixtureName ? options.fixtureName : 'wrong-proposal-shape',
                errors: requestValidation.errors
            };
        }
        const fixtureName = options && options.fixtureName ? options.fixtureName : request.intent;
        const rawText = fixtureName === 'malformed-json'
            ? malformedJsonFixture
            : fixtureName === 'wrong-proposal-shape'
                ? JSON.stringify(wrongProposalShapeFixture, null, 2)
                : JSON.stringify(getFixtureProposal(fixtureName, request.id, options ? options.proposalId : undefined), null, 2);
        const parsed = GrafcetStudioAIProposalParser.parseAiProposalResponse(rawText);
        return parsed.ok
            ? { ok: true, rawText, proposal: parsed.value, fixtureName, errors: [] }
            : { ok: false, rawText, fixtureName, errors: parsed.errors };
    }
    GrafcetStudioAIMockService.generateMockResponse = generateMockResponse;
    function receiveHostResponse(rawText) {
        if (typeof rawText !== 'string' || !rawText.trim()) {
            return { ok: false, rawText: rawText || '', fixtureName: 'wrong-proposal-shape', errors: ['Host AI response must be a non-empty JSON string.'] };
        }
        const parsed = GrafcetStudioAIProposalParser.parseAiProposalResponse(rawText);
        if (!parsed.ok || !parsed.value) {
            const fixtureName = parsed.jsonText ? 'wrong-proposal-shape' : 'malformed-json';
            return { ok: false, rawText, fixtureName, errors: parsed.errors };
        }
        return { ok: true, rawText, proposal: parsed.value, fixtureName: parsed.value.intent, errors: [] };
    }
    GrafcetStudioAIMockService.receiveHostResponse = receiveHostResponse;
    function validateMockFixtures() {
        const errors = [];
        const validFixturesThatPassed = [];
        const invalidFixturesThatFailed = [];
        validFixtureNames.forEach(function (intent) {
            const validation = GrafcetStudioAIContracts.validateAiProposal(validFixtures[intent]);
            if (validation.ok)
                validFixturesThatPassed.push(intent);
            else
                errors.push(intent + ' fixture should pass validation: ' + validation.errors.join('; '));
        });
        try {
            JSON.parse(malformedJsonFixture);
            errors.push('malformed-json fixture should fail JSON.parse.');
        }
        catch (_error) {
            invalidFixturesThatFailed.push('malformed-json');
        }
        const wrongShapeValidation = GrafcetStudioAIContracts.validateAiProposal(wrongProposalShapeFixture);
        if (!wrongShapeValidation.ok)
            invalidFixturesThatFailed.push('wrong-proposal-shape');
        else
            errors.push('wrong-proposal-shape fixture should fail AiProposal validation.');
        return {
            ok: errors.length === 0,
            validFixtures: validFixturesThatPassed,
            invalidFixtures: invalidFixturesThatFailed,
            errors
        };
    }
    GrafcetStudioAIMockService.validateMockFixtures = validateMockFixtures;
    GrafcetStudioAIMockService.api = {
        fixtures: allFixtureNames,
        getFixtureRawText,
        getFixtureProposal,
        generateMockResponse,
        receiveHostResponse,
        validateMockFixtures
    };
})(GrafcetStudioAIMockService || (GrafcetStudioAIMockService = {}));
