using GrafcetStudio.App.Events;
using Prism.Events;
using System;
using System.Text.Json;
using System.Threading.Tasks;

namespace GrafcetStudio.App.Services;

public class MockAiService
{
    private const string SchemaVersion = "1.0.0";
    private readonly IWebViewBridgeService _webViewBridgeService;

    public MockAiService(IEventAggregator eventAggregator, IWebViewBridgeService webViewBridgeService)
    {
        _webViewBridgeService = webViewBridgeService;
        eventAggregator.GetEvent<AiRequestedEvent>().Subscribe(async payload => await HandleAiRequestAsync(payload));
    }

    private async Task HandleAiRequestAsync(AiRequestPayload payload)
    {
        var request = TryReadRequest(payload);
        var rawResponse = request.FixtureName switch
        {
            "malformed-json" => BuildMalformedJsonFixture(),
            "wrong-proposal-shape" => BuildWrongProposalShapeFixture(),
            _ => BuildProposalFixture(request.Intent, request.RequestId)
        };

        await _webViewBridgeService.SendAiChunkAsync(rawResponse);
        await _webViewBridgeService.SendAiChunkAsync("__STREAM_END__");
    }

    private static MockRequest TryReadRequest(AiRequestPayload payload)
    {
        var request = new MockRequest(
            NormalizeIntent(payload.Type),
            string.Empty,
            NormalizeFixtureName(payload.Type));

        var rawJson = !string.IsNullOrWhiteSpace(payload.RequestJson)
            ? payload.RequestJson
            : payload.DiagramContext;

        if (string.IsNullOrWhiteSpace(rawJson)) return request;

        try
        {
            using var doc = JsonDocument.Parse(rawJson);
            var root = doc.RootElement;
            var intent = GetOptionalString(root, "intent");
            var requestId = GetOptionalString(root, "id");
            var fixtureName = GetOptionalString(root, "fixtureName", "mockFixture");

            return new MockRequest(
                NormalizeIntent(intent, request.Intent),
                requestId,
                NormalizeFixtureName(fixtureName, request.FixtureName));
        }
        catch (JsonException)
        {
            return request;
        }
    }

    private static string NormalizeIntent(string? value, string fallback = "create-variable")
        => value switch
        {
            "clone-variable" => "clone-variable",
            "map-io" => "map-io",
            "create-flow" => "create-flow",
            _ => fallback
        };

    private static string NormalizeFixtureName(string? value, string fallback = "")
        => value switch
        {
            "malformed-json" => "malformed-json",
            "wrong-proposal-shape" => "wrong-proposal-shape",
            _ => fallback
        };

    private static string GetOptionalString(JsonElement element, params string[] propertyNames)
    {
        foreach (var propertyName in propertyNames)
        {
            if (element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String)
            {
                return property.GetString() ?? string.Empty;
            }
        }

        return string.Empty;
    }

    private static string BuildMalformedJsonFixture()
        => "{ \"schemaVersion\": \"" + SchemaVersion + "\", \"intent\": \"create-variable\", \"data\": { ";

    private static string BuildWrongProposalShapeFixture()
        => JsonSerializer.Serialize(new
        {
            schemaVersion = SchemaVersion,
            id = "ai-prop-mock-wrong-shape",
            intent = "create-variable",
            status = "draft",
            summary = "This mock fixture intentionally fails AiProposal validation because data.variable is malformed.",
            data = new
            {
                variable = new
                {
                    label = string.Empty,
                    address = 123
                }
            }
        });

    private static string BuildProposalFixture(string intent, string requestId)
        => intent switch
        {
            "clone-variable" => SerializeProposal("ai-prop-mock-clone-variable", intent, requestId, new
            {
                source = new { label = "Existing_StartCommand" },
                variable = new
                {
                    label = "Mock_StartCommand_Clone",
                    format = "BOOL",
                    address = "MR101",
                    kind = "primitive",
                    dataType = "BOOL",
                    comment = "Generated by mock AI fixture for clone-variable.",
                    source = "manual"
                }
            }, "Mock proposal clones a selected variable with a new label and address."),
            "map-io" => SerializeProposal("ai-prop-mock-map-io", intent, requestId, new
            {
                entries = new[]
                {
                    new { physicalIOId = "mock-io-start-button", appVariable = "Mock_StartCommand", status = "mapped", matchScore = 0.95 }
                }
            }, "Mock proposal maps one physical IO point to an application variable."),
            "create-flow" => SerializeProposal("ai-prop-mock-create-flow", intent, requestId, new
            {
                flow = new
                {
                    id = "mock-flow-basic-cycle",
                    name = "Mock Basic Cycle",
                    type = "Grafcet",
                    mode = "Auto",
                    steps = new object[]
                    {
                        new { id = "mock-step-idle", number = 1, label = "Idle", initial = true, actions = Array.Empty<object>() },
                        new { id = "mock-step-run", number = 2, label = "Run", initial = false, actions = new[] { new { variable = "Mock_StartCommand", qualifier = "N", address = "MR100" } } }
                    },
                    transitions = new[]
                    {
                        new { id = "mock-trans-start", label = "Start", condition = "Mock_StartCommand", fromStepIds = new[] { "mock-step-idle" }, toStepIds = new[] { "mock-step-run" } }
                    },
                    connections = new[]
                    {
                        new { from = "mock-step-idle", to = "mock-trans-start" },
                        new { from = "mock-trans-start", to = "mock-step-run" }
                    }
                }
            }, "Mock proposal creates a minimal two-step flow skeleton."),
            _ => SerializeProposal("ai-prop-mock-create-variable", "create-variable", requestId, new
            {
                bucket = "user",
                variable = new
                {
                    label = "Mock_StartCommand",
                    format = "BOOL",
                    address = "MR100",
                    kind = "primitive",
                    dataType = "BOOL",
                    comment = "Generated by mock AI fixture for create-variable.",
                    source = "manual"
                }
            }, "Mock proposal creates one manual boolean variable for parser, preview, and apply tests.")
        };

    private static string SerializeProposal(string id, string intent, string requestId, object data, string summary)
        => JsonSerializer.Serialize(new
        {
            schemaVersion = SchemaVersion,
            id,
            intent,
            status = "draft",
            requestId = string.IsNullOrWhiteSpace(requestId) ? null : requestId,
            summary,
            warnings = new[] { "Mock fixture only; no project mutation has been performed." },
            data
        });

    private sealed record MockRequest(string Intent, string RequestId, string FixtureName);
}
