function cgGetPayloadApi() {
  return window.GrafcetStudio && window.GrafcetStudio.codegenPayload;
}

function cgBuildPayloadContext() {
  return {
    project,
    loadDiagramData,
    getAssets: cgGetCodegenAssets,
    ensureFlowAddressConfig: typeof ensureFlowAddressConfig === 'function' ? ensureFlowAddressConfig : undefined,
    ensureProjectVariables: typeof ensureProjectVariables === 'function' ? ensureProjectVariables : undefined,
    syncVariableSignalAddressesFromDeviceTypes: typeof syncVariableSignalAddressesFromDeviceTypes === 'function' ? syncVariableSignalAddressesFromDeviceTypes : undefined,
    saveProject: typeof saveProject === 'function' ? saveProject : undefined,
    getDefaultUnitId: cgGetDefaultUnitId,
    unitSignals: typeof GVT_UNIT_SIGNALS !== 'undefined' ? GVT_UNIT_SIGNALS : [],
    projectUnitStructSignals: typeof PROJECT_UNIT_STRUCT_SIGNALS !== 'undefined' ? PROJECT_UNIT_STRUCT_SIGNALS : []
  };
}

function resolveStepAddress(step, flow) {
  return cgGetPayloadApi().resolveStepAddress(step, flow);
}

function cgValidateUnitAddressConfig(unitDiagrams) {
  return cgGetPayloadApi().validateUnitAddressConfig(cgBuildPayloadContext(), unitDiagrams);
}

function cgBuildCSharpPayload(platform, unitId) {
  if (typeof gvtFlushFocusedAddressInput === 'function') gvtFlushFocusedAddressInput();
  if (activeDiagramId && typeof flushState === 'function') flushState();
  return cgGetPayloadApi().buildCSharpPayload(cgBuildPayloadContext(), platform, unitId || cgGetDefaultUnitId() || '');
}

function cgBuildCSharpFlow(diagId) {
  return cgGetPayloadApi().buildCSharpFlow(cgBuildPayloadContext(), diagId);
}

function cgBuildCSharpUnitPayload(platform, unitId) {
  return cgGetPayloadApi().buildCSharpUnitPayload(cgBuildPayloadContext(), platform, unitId);
}
function cgGenerateSelectedUnit() {
  const target = document.getElementById('cg-target')?.value || 'unit-config';
  const platform = cgResolveHostPlatform(target);
  const unitId = cgGetDefaultUnitId();
  if (!unitId) {
    const pre = document.getElementById('cg-files');
    const stat = document.getElementById('cg-stat');
    if (pre) pre.textContent = 'No unit selected.';
    if (stat) stat.textContent = 'No unit selected';
    return false;
  }
  return cgGenerateViaHost(platform, unitId);
}
function cgGenerateViaHost(platform, diagId) {
  if (!(window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === 'function')) {
    const pre = document.getElementById('cg-files');
    const stat = document.getElementById('cg-stat');
    if (pre) pre.textContent = 'C# generator is available only inside the WPF host.';
    if (stat) stat.textContent = 'Host bridge unavailable';
    return false;
  }

  try {
    window.chrome.webview.postMessage({
      type: 'GENERATE_CODE',
      payload: cgBuildCSharpPayload(platform, diagId)
    });
    return true;
  } catch (err) {
    const pre = document.getElementById('cg-files');
    const stat = document.getElementById('cg-stat');
    const message = err && err.message ? err.message : String(err);
    if (pre) pre.textContent = 'Payload validation error: ' + message;
    if (stat) stat.textContent = 'Payload validation failed';
    if (typeof toast === 'function') toast('? ' + message);
    return false;
  }
}

function receiveGeneratedCode(output) {
  const pre = document.getElementById('cg-files');
  const stat = document.getElementById('cg-stat');
  const files = output && Array.isArray(output.files) ? output.files : null;

  if (!files) {
    if (pre) pre.textContent = output || '';
  } else if (typeof cgRenderGeneratedFiles === 'function') {
    cgRenderGeneratedFiles(files);
  } else if (pre) {
    pre.textContent = files.map(file => {
      const path = file && file.path ? file.path : 'Untitled.st';
      const content = file && file.content ? file.content : '';
      return '// FILE: ' + path + '\n' + content;
    }).join('\n\n');
  }

  if (stat) stat.textContent = files ? 'Generated ' + files.length + ' file(s) by C# host' : 'Generated by C# host';
}

function receiveError(payload) {
  const pre = document.getElementById('cg-files');
  const stat = document.getElementById('cg-stat');
  const source = payload && payload.source ? payload.source : 'host';
  const message = payload && payload.message ? payload.message : String(payload || 'Unknown error');
  if (typeof toast === 'function' && (source === 'template-loader' || source === 'template-validation')) {
    toast('? ' + source + ': ' + message);
  }
  if (pre) pre.textContent = source + ' error: ' + message;
  if (stat) stat.textContent = 'C# host error';
}

function cgUCHighlight(pre, profile) {
  const commentPfx = profile ? profile.comment : ';';
  const commentRe = commentPfx === '//' ? /^(\/\/.*)$/gm : /^(;.*)$/gm;
  const escaped = pre.textContent.replace(/[&<>]/g, c =>
    c === '&' ? '&amp;' : c === '<' ? '&lt;' : '&gt;');
  pre.innerHTML = escaped
    .replace(/^(;&lt;h1\/&gt;.*)$/gm, '<span style="color:var(--amber);font-weight:bold">$1</span>')
    .replace(commentRe, '<span style="color:var(--text3)">$1</span>')
    .replace(/\b(LDP|LDB|ANP|ANF|ALT|DIFU|ZRES|CON|MPS|MRD|MPP|LD|SET|RES|RST|OUT|AND|ANB|OR|ORL|ANL|ONDL|MOV)\b/g,
      '<span style="color:var(--cyan)">$1</span>')
    .replace(/@MR\d+/g, '<span style="color:var(--amber)">$&</span>')
    .replace(/\bMR\d+\b/g, '<span style="color:#4ade80">$&</span>')
    .replace(/\bLR\d+\b/g, '<span style="color:#f472b6">$&</span>');
}
