using System.Text.Json;

namespace GrafcetStudio.App.Services.Ai;

public class MockAiCompletionService : IAiCompletionService
{
    public Task<AiCompletionResult> CompleteAsync(AiCompletionRequest request, CancellationToken cancellationToken = default)
    {
        var rawResponse = BuildRawResponse(request);
        return Task.FromResult(AiCompletionResult.Success(rawResponse));
    }

    public async IAsyncEnumerable<AiStreamChunk> StreamAsync(AiCompletionRequest request, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        yield return AiStreamChunk.Status("Mock streaming request accepted.");
        await Task.Delay(10, cancellationToken);

        if (request.FixtureName == "stream-timeout")
        {
            yield return AiStreamChunk.Status("Mock streaming timeout fixture started.");
            await Task.Delay(TimeSpan.FromSeconds(10), cancellationToken);
        }

        if (request.FixtureName == "stream-cancel")
        {
            yield return AiStreamChunk.Status("Mock streaming cancel fixture started.");
            throw new OperationCanceledException(cancellationToken);
        }

        if (request.FixtureName == "stream-error")
        {
            yield return AiStreamChunk.Status("Mock streaming error fixture started.");
            throw new InvalidOperationException("Mock streaming service error.");
        }

        var rawResponse = BuildRawResponse(request);
        yield return AiStreamChunk.Status("Mock streaming proposal JSON.");

        foreach (var chunk in SplitJson(rawResponse, request.FixtureName == "partial-json" ? 17 : 48))
        {
            cancellationToken.ThrowIfCancellationRequested();
            yield return AiStreamChunk.Delta(chunk);
            await Task.Delay(2, cancellationToken);
        }

        yield return AiStreamChunk.Final(rawResponse);
    }

    private static IEnumerable<string> SplitJson(string text, int chunkSize)
    {
        for (var index = 0; index < text.Length; index += chunkSize)
        {
            yield return text.Substring(index, Math.Min(chunkSize, text.Length - index));
        }
    }

    private static string BuildRawResponse(AiCompletionRequest request)
        => request.FixtureName switch
        {
            "malformed-json" => BuildMalformedJsonFixture(),
            "wrong-proposal-shape" => BuildWrongProposalShapeFixture(),
            _ => BuildProposalFixture(request.Request.Intent, request.Request.Id)
        };

    private static string BuildMalformedJsonFixture()
        => "{ \"schemaVersion\": \"" + AiContractGuard.SchemaVersion + "\", \"intent\": \"create-variable\", \"data\": { ";

    private static string BuildWrongProposalShapeFixture()
        => JsonSerializer.Serialize(new
        {
            schemaVersion = AiContractGuard.SchemaVersion,
            id = "ai-prop-mock-wrong-shape",
            intent = "create-variable",
            status = "draft",
            summary = "This mock fixture intentionally fails AiProposal validation because data.variable is malformed.",
            data = new
            {
                variable = new
                {
                    label = string.Empty,
                    address = 123
                }
            }
        });

    private static string BuildProposalFixture(string intent, string requestId)
        => intent switch
        {
            "clone-variable" => SerializeProposal("ai-prop-mock-clone-variable", intent, requestId, new
            {
                source = new { label = "Existing_StartCommand" },
                variable = new
                {
                    label = "Mock_StartCommand_Clone",
                    format = "BOOL",
                    address = "MR101",
                    kind = "primitive",
                    dataType = "BOOL",
                    comment = "Generated by mock AI fixture for clone-variable.",
                    source = "manual"
                }
            }, "Mock proposal clones a selected variable with a new label and address."),
            "map-io" => SerializeProposal("ai-prop-mock-map-io", intent, requestId, new
            {
                entries = new[]
                {
                    new { physicalIOId = "mock-io-start-button", appVariable = "Mock_StartCommand", status = "mapped", matchScore = 0.95 }
                }
            }, "Mock proposal maps one physical IO point to an application variable."),

            "create-structure" => SerializeProposal("ai-prop-mock-create-structure", intent, requestId, new
            {
                name = "ServoAxis",
                signals = new[]
                {
                    new { name = "Enable", dataType = "Bool", varType = "Output", comment = "Enable servo axis" },
                    new { name = "Ready", dataType = "Bool", varType = "Input", comment = "Servo ready signal" },
                    new { name = "Fault", dataType = "Bool", varType = "Input", comment = "Servo fault signal" }
                }
            }, "Mock proposal creates a ServoAxis struct with Enable and Ready signals."),
            "create-flow" => SerializeProposal("ai-prop-mock-create-flow", intent, requestId, new
            {
                flow = new
                {
                    id = "mock-flow-basic-cycle",
                    name = "Mock Basic Cycle",
                    type = "Grafcet",
                    mode = "Auto",
                    steps = new object[]
                    {
                        new { id = "mock-step-idle", number = 1, label = "Idle", initial = true, actions = Array.Empty<object>() },
                        new { id = "mock-step-run", number = 2, label = "Run", initial = false, actions = new[] { new { variable = "Mock_StartCommand", qualifier = "N", address = "MR100" } } }
                    },
                    transitions = new[]
                    {
                        new { id = "mock-trans-start", label = "Start", condition = "Mock_StartCommand", fromStepIds = new[] { "mock-step-idle" }, toStepIds = new[] { "mock-step-run" } }
                    },
                    connections = new[]
                    {
                        new { from = "mock-step-idle", to = "mock-trans-start" },
                        new { from = "mock-trans-start", to = "mock-step-run" }
                    }
                }
            }, "Mock proposal creates a minimal two-step flow skeleton."),
            _ => SerializeProposal("ai-prop-mock-create-variable", "create-variable", requestId, new
            {
                bucket = "user",
                variable = new
                {
                    label = "Mock_StartCommand",
                    format = "BOOL",
                    address = "MR100",
                    kind = "primitive",
                    dataType = "BOOL",
                    comment = "Generated by mock AI fixture for create-variable.",
                    source = "manual"
                }
            }, "Mock proposal creates one manual boolean variable for parser, preview, and apply tests.")
        };

    private static string SerializeProposal(string id, string intent, string requestId, object data, string summary)
        => JsonSerializer.Serialize(new
        {
            schemaVersion = AiContractGuard.SchemaVersion,
            id,
            intent,
            status = "draft",
            requestId = string.IsNullOrWhiteSpace(requestId) ? null : requestId,
            summary,
            warnings = new[] { "Mock fixture only; no project mutation has been performed." },
            data
        });
}
