using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace GrafcetStudio.App.Generators.Robot;

public class RapidRenderer
{
    public string Render(RobotIrDocument doc, string moduleName = "MainModule")
    {
        var sb = new StringBuilder();
        var modName = string.IsNullOrWhiteSpace(doc.Module) ? moduleName : doc.Module;

        sb.AppendLine($"MODULE {modName}");
        sb.AppendLine("    ! ============================================");
        sb.AppendLine("    ! Generated by GrafectStudio (ABB RAPID Generator)");
        sb.AppendLine($"    ! Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("    ! WARNING: Teach all positions on pendant before running!");
        sb.AppendLine("    ! ============================================");
        sb.AppendLine();

        // 1. Signal Aliases
        if (doc.Signals.Count > 0)
        {
            sb.AppendLine("    ! --- Signal Declarations ---");
            foreach (var sig in doc.Signals)
            {
                var sigType = sig.Type.ToUpperInvariant();
                var aliasStr = string.IsNullOrWhiteSpace(sig.Alias) ? sig.Name : sig.Alias;
                sb.AppendLine($"    ALIAS {sigType} {sig.Name} := {aliasStr};");
            }
            sb.AppendLine();
        }

        // 2. Positions (robtarget)
        if (doc.Positions.Count > 0)
        {
            sb.AppendLine("    ! --- Position Declarations (DEFAULT SAFE VALUES - MUST BE TAUGHT) ---");
            foreach (var pos in doc.Positions)
            {
                sb.AppendLine($"    PERS robtarget {pos.Name} := [[0,0,500],[1,0,0,0],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]]; ! ⚠ TEACH");
            }
            sb.AppendLine();
        }

        // 3. Tools (tooldata)
        var tools = doc.Tools.Count > 0 ? doc.Tools : new List<RobotTool> { new RobotTool { Name = "tool1" } };
        sb.AppendLine("    ! --- Tool Declarations (DEFAULT TCP - MUST BE CALIBRATED) ---");
        foreach (var t in tools)
        {
            sb.AppendLine($"    PERS tooldata {t.Name} := [TRUE,[[0,0,100],[1,0,0,0]],[0.5,[0,0,50],[1,0,0,0],0,0,0]]; ! ⚠ CALIBRATE");
        }
        sb.AppendLine();

        // 4. Main Procedure
        sb.AppendLine("    PROC main()");

        // Init block
        if (doc.Init?.Instructions != null && doc.Init.Instructions.Count > 0)
        {
            sb.AppendLine("        ! === INITIALIZATION ===");
            foreach (var instr in doc.Init.Instructions)
            {
                RenderInstruction(sb, instr, "        ");
            }
            sb.AppendLine();
        }

        // Main Loop
        sb.AppendLine("        WHILE TRUE DO");
        foreach (var step in doc.Steps)
        {
            sb.AppendLine($"            ! === STEP {step.Id}: {step.Name} ===");
            if (step.Instructions != null)
            {
                foreach (var instr in step.Instructions)
                {
                    RenderInstruction(sb, instr, "            ");
                }
            }
            sb.AppendLine();
        }
        sb.AppendLine("        ENDWHILE");

        sb.AppendLine("    ENDPROC");
        sb.AppendLine();
        sb.AppendLine("ENDMODULE");

        return sb.ToString();
    }

    private void RenderInstruction(StringBuilder sb, RobotInstruction instr, string indent)
    {
        var type = instr.Type?.Trim() ?? string.Empty;
        var tool = string.IsNullOrWhiteSpace(instr.Tool) ? "tool1" : instr.Tool;

        var (speedData, zoneData) = GetSpeedAndZone(instr);

        switch (type.ToUpperInvariant())
        {
            case "MOVEJ":
                sb.AppendLine($"{indent}MoveJ {FormatTarget(instr)}, {speedData}, {zoneData}, {tool};");
                break;

            case "MOVEL":
                sb.AppendLine($"{indent}MoveL {FormatTarget(instr)}, {speedData}, {zoneData}, {tool};");
                break;

            case "MOVEABSJ":
                sb.AppendLine($"{indent}MoveAbsJ {instr.Target}, {speedData}, fine, {tool};");
                break;

            case "SETDO":
                sb.AppendLine($"{indent}SetDO {instr.Signal}, {FormatValue(instr.Value)};");
                break;

            case "WAITDI":
                sb.AppendLine($"{indent}WaitDI {instr.Signal}, {FormatValue(instr.Value)};");
                break;

            case "WAITTIME":
                var sec = instr.Seconds ?? 0.5;
                sb.AppendLine($"{indent}WaitTime {sec.ToString(CultureInfo.InvariantCulture)};");
                break;

            case "SETAO":
                sb.AppendLine($"{indent}SetAO {instr.Signal}, {FormatValue(instr.Value)};");
                break;

            case "WAITAI":
                sb.AppendLine($"{indent}WaitAI {instr.Signal}, {FormatValue(instr.Value)};");
                break;

            default:
                sb.AppendLine($"{indent}! Unknown instruction type: {instr.Type}");
                break;
        }
    }

    private string FormatTarget(RobotInstruction instr)
    {
        if (instr.Offset != null && (instr.Offset.X != null || instr.Offset.Y != null || instr.Offset.Z != null))
        {
            var xStr = FormatOffsetVal(instr.Offset.X);
            var yStr = FormatOffsetVal(instr.Offset.Y);
            var zStr = FormatOffsetVal(instr.Offset.Z);
            return $"Offs({instr.Target}, {xStr}, {yStr}, {zStr})";
        }
        return instr.Target ?? "pHome";
    }

    private string FormatOffsetVal(object? val)
    {
        if (val == null) return "0";
        if (val is JsonElement je)
        {
            if (je.ValueKind == JsonValueKind.Number) return je.GetRawText();
            if (je.ValueKind == JsonValueKind.String) return je.GetString() ?? "0";
        }
        return val.ToString() ?? "0";
    }

    private string FormatValue(object? val)
    {
        if (val == null) return "0";
        if (val is JsonElement je)
        {
            if (je.ValueKind == JsonValueKind.Number) return je.GetRawText();
            if (je.ValueKind == JsonValueKind.True) return "1";
            if (je.ValueKind == JsonValueKind.False) return "0";
            if (je.ValueKind == JsonValueKind.String) return je.GetString() ?? "0";
        }
        return val.ToString() ?? "0";
    }

    private (string Speed, string Zone) GetSpeedAndZone(RobotInstruction instr)
    {
        // Default mapping:
        // Fast -> v500, z50
        // Medium -> v300, z10
        // Precise -> v100, fine
        return ("v300", "z10");
    }
}
